defaults:
  - backbone: vgg19

random_seed: 26
mode:
  train:
    batch_size: 64
    max_epochs: 3
    shuffle: True
  val:
    batch_size: 64
    max_epochs: 1
    shuffle: False

# Directories
dirs:
  data: ./data